// Korean translations for user-facing text. English strings remain the stable source keys.
export const koreanTranslations: Record<string, string> = {
    " [L]": " [고정]",
    " Comet Fan": " 부채꼴 혜성",
    " Comet Mine": " 혜성 분사",
    " Crackle": " 타닥불꽃",
    " Flying Fish": " 날치 효과",
    " Fountain": " 분수",
    " Info": " 설명",
    " Micro Burst": " 소형 폭발",
    " Palm": " 야자수형 폭발",
    " Ring": " 고리형 폭발",
    " Shell of Shells": " 자탄 폭발",
    " Sphere": " 구형 폭발",
    " Spray Burst": " 분사 폭발",
    " Spray Fan": " 부채꼴 분사",
    " Spray Mine": " 입자 분사",
    " Star": " 별형 폭발",
    " Tourbillion Rising Wisp": " 상승 회오리",
    "(A sequence cannot contain itself.)\n\nOnce more the left panel is the editor, and the right panel the list.\nNaming is still important, even here.\n\nYou begin your first sequence by adding a shell or ground effect.": "(시퀀스는 자기 자신을 포함할 수 없습니다.)\n왼쪽 패널은 편집기이고 오른쪽은 목록입니다.\n여기서도 알아보기 쉬운 이름이 중요합니다.\n폭죽탄이나 지상 효과를 추가해 첫 시퀀스를 시작하세요.",
    "(no dates)": "(날짜 없음)",
    "[Empty]": "[비어 있음]",
    "[No rides]": "[놀이기구 없음]",
    "[None]": "[없음]",
    "[Unnamed]": "[이름 없음]",
    "{BLACK}Debugger": "{BLACK}디버거",
    "{BLACK}Start Show Programme": "{BLACK}공연 프로그램 시작",
    "{RED}Compact Sub-Sequences": "{RED}하위 시퀀스 접기",
    "{RED}Stop": "{RED}중지",
    "{RED}Warning: The debug window may cause lag.": "{RED}경고: 디버거 창이 렉을 유발할 수 있습니다.",
    "{RED}Yes": "{RED}예",
    "{TOPAZ}Delay": "{TOPAZ}지연",
    "{TOPAZ}Time": "{TOPAZ}시간",
    "{WHITE}Add": "{WHITE}추가",
    "{WHITE}Add / Update": "{WHITE}추가 / 업데이트",
    "{WHITE}Add Date": "{WHITE}날짜 추가",
    "{WHITE}Add Ground Effect": "{WHITE}지상 효과 추가",
    "{WHITE}Add Load": "{WHITE}효과 묶음 추가",
    "{WHITE}Add Shell": "{WHITE}폭죽탄 추가",
    "{WHITE}Add Show": "{WHITE}공연 추가",
    "{WHITE}Add Site": "{WHITE}지점 추가",
    "{WHITE}An attempt has been made to load, but some or all features may be broken.": "{WHITE}불러오기를 시도했지만 일부 또는 모든 기능이 정상 작동하지 않을 수 있습니다.",
    "{WHITE}Are you sure?": "{WHITE}정말 진행할까요?",
    "{WHITE}Attempted Fireworks Lit: {WHITE}": "{WHITE}실행 시도 불꽃: {WHITE}",
    "{WHITE}Attempted Particles: {WHITE}": "{WHITE}생성 시도 입자: {WHITE}",
    "{WHITE}Auto Switch Palettes: {GREEN}ON": "{WHITE}자동 팔레트 전환: {GREEN}켜짐",
    "{WHITE}Auto Switch Palettes: OFF": "{WHITE}자동 팔레트 전환: 꺼짐",
    "{WHITE}Default Palette": "{WHITE}기본 팔레트",
    "{WHITE}Delay": "{WHITE}지연",
    "{WHITE}Delayed Fireworks: {WHITE}": "{WHITE}지연된 불꽃: {WHITE}",
    "{WHITE}Delete": "{WHITE}삭제",
    "{WHITE}Delete all data": "{WHITE}모든 데이터 삭제",
    "{WHITE}Delete cascading": "{WHITE}연결된 항목도 삭제",
    "{WHITE}Delete G.E.": "{WHITE}지상 효과 삭제",
    "{WHITE}Delete Load": "{WHITE}효과 묶음 삭제",
    "{WHITE}Delete Shell": "{WHITE}폭죽탄 삭제",
    "{WHITE}Delete Show": "{WHITE}공연 삭제",
    "{WHITE}Delete Site": "{WHITE}지점 삭제",
    "{WHITE}Delete, leave references": "{WHITE}참조를 남기고 삭제",
    "{WHITE}Details": "{WHITE}세부 정보",
    "{WHITE}Discard unsaved changes?": "{WHITE}저장하지 않은 변경 사항을 버릴까요?",
    "{WHITE}Download the new version from\n": "{WHITE}새 버전 다운로드:\n",
    "{WHITE}Duration": "{WHITE}지속 시간",
    "{WHITE}Fireworks Plugin": "{WHITE}불꽃놀이 플러그인",
    "{WHITE}How would you like to proceed?": "{WHITE}어떻게 처리하시겠습니까?",
    "{WHITE}Icons": "{WHITE}아이콘",
    "{WHITE}Import Add": "{WHITE}추가로 가져오기",
    "{WHITE}Import Overwrite": "{WHITE}덮어써서 가져오기",
    "{WHITE}Launch Site": "{WHITE}발사 지점",
    "{WHITE}Name": "{WHITE}이름",
    "{WHITE}New": "{WHITE}새로 만들기",
    "{WHITE}Next": "{WHITE}다음",
    "{WHITE}Next after": "{WHITE}다음 실행 기준",
    "{WHITE}On": "{WHITE}활성",
    "{WHITE}Remove Date": "{WHITE}날짜 제거",
    "{WHITE}Remove Load": "{WHITE}효과 묶음 제거",
    "{WHITE}Reset Counts": "{WHITE}수치 초기화",
    "{WHITE}Restore Palette": "{WHITE}팔레트 복원",
    "{WHITE}Save": "{WHITE}저장",
    "{WHITE}Select": "{WHITE}선택",
    "{WHITE}Set Trigger": "{WHITE}실행 조건 설정",
    "{WHITE}Show": "{WHITE}공연",
    "{WHITE}Skipped Fireworks: {WHITE}": "{WHITE}건너뛴 불꽃: {WHITE}",
    "{WHITE}Skipped Particles: {WHITE}": "{WHITE}생성 실패 입자: {WHITE}",
    "{WHITE}Some names exist in both datasets:": "{WHITE}두 데이터에 같은 이름이 있습니다:",
    "{WHITE}Test Ground Effect": "{WHITE}지상 효과 시험",
    "{WHITE}Test Load": "{WHITE}효과 묶음 시험",
    "{WHITE}Test Shell": "{WHITE}폭죽탄 시험",
    "{WHITE}Test Show": "{WHITE}공연 시험",
    "{WHITE}This will permanently delete all fireworks data.": "{WHITE}모든 불꽃놀이 데이터가 영구적으로 삭제됩니다.",
    "{WHITE}Time": "{WHITE}시간",
    "{WHITE}Type": "{WHITE}종류",
    "{WHITE}Update Show": "{WHITE}공연 업데이트",
    "{WHITE}Which version would you like to keep?": "{WHITE}어느 버전을 유지하시겠습니까?",
    "{WHITE}Yes": "{WHITE}예",
    "2 Gradual Phase Fountain": "2단계 점진형 분수",
    "3 Sharp Phase Fountain": "3단계 급변형 분수",
    "A blinking sphere": "깜박이는 구형 폭발",
    "A blinking sphere of four zones, like\norange slices": "오렌지 조각처럼 네 구역이\n깜박이는 구형 폭발",
    "A blinking sphere of six zones, like a die": "주사위처럼 여섯 구역이 깜박이는 구형 폭발",
    "A blinking sphere of two halves": "두 반구가 깜박이는 구형 폭발",
    "A burst of headless comets that starts of much like a palm,\nuntil the heads suddenly light up, and the comets proppel themselves\nin random directions, like a school of fish darting off.": "머리 없는 혜성들이 야자수처럼 퍼지다가 머리가 갑자기 빛나며,\n물고기 떼가 흩어지듯 무작위 방향으로 빠르게 움직입니다.",
    "A burst of particles is shot from a point.": "한 지점에서 입자가 폭발하듯 발사됩니다.",
    "A cluster of comets fired outward, arcing down like the\ndrooping leaves of a palm tree.\n": "혜성 무리가 바깥쪽으로 퍼져 나간 뒤\n야자수 잎처럼 아래로 휘어집니다.\n",
    "A colour sequence is used for the heads\nTrail colour set seperate": "머리에 색상 시퀀스를 사용합니다.\n꼬리 색상은 별도로 설정합니다.",
    "A colour sequence is used for the trails.\nHead colour set seperate": "꼬리에 색상 시퀀스를 사용합니다.\n머리 색상은 별도로 설정합니다.",
    "A colour sequence is used the full comets": "혜성 전체에 색상 시퀀스를 사용합니다.",
    "A colour sequence is used to create horizontal\nlayers,like a rainbow": "색상 시퀀스로 무지개 같은\n수평 층을 만듭니다.",
    "A colour sequence is used to create vertical\nstripes, like the French flag": "색상 시퀀스로 프랑스 국기 같은\n수직 줄무늬를 만듭니다.",
    "A continuous spray of particles made up of one or more\nphases played back to back that gradually transition from one to the next.": "하나 이상의 단계를 연속 재생하며 입자를 계속 분사합니다.\n각 단계는 다음 단계로 점차 전환됩니다.",
    "A custom-load shell of shells effect needs at least one load.": "사용자 효과 묶음을 쓰는 자탄 폭발에는 효과 묶음이 하나 이상 필요합니다.",
    "A fan of comets is launched from a point.": "한 지점에서 혜성을 부채꼴로 발사합니다.",
    "A ground effect must have a selected launch site.": "지상 효과에는 발사 지점을 선택해야 합니다.",
    "A ground effect must have at least one effect.": "지상 효과에는 효과가 하나 이상 필요합니다.",
    "A load must have at least one effect.": "효과 묶음에는 효과가 하나 이상 필요합니다.",
    "A ring of alternating two colours": "두 색상이 번갈아 배치된 고리",
    "A ring of alternating two colours that\nchange halfway through": "두 색상이 번갈아 배치되고\n도중에 색상이 바뀌는 고리",
    "A ring of clumps of particles, possibly with a trail, and possibly bursting at the end.\n": "입자 무리가 고리 모양으로 퍼집니다. 꼬리를 남기거나 끝에서 폭발하게 할 수 있습니다.\n",
    "A ring of colours arranged according to a\nsequence": "색상 시퀀스에 따라 배치된 고리",
    "A ring of one colour": "한 색상의 고리",
    "A ring of one colour that changes colour\nhalfway through": "도중에 색상이 바뀌는 단색 고리",
    "A sequence must have at least one item.": "시퀀스에는 항목이 하나 이상 필요합니다.",
    "A shell can also have additional loads, 'Ascend Loads', which will be set off\non the way up with a certain delay. This is optional, and only recommended for\nthe largest of main loads and high up shells, if you're going for realism\nanyway.\n\n": "폭죽탄이 상승하는 동안 일정 지연 후 실행되는 '상승 효과'도 넣을 수 있습니다.\n선택 사항이며 사실적인 연출을 원한다면 큰 주 효과 묶음과\n높이 올라가는 폭죽탄에 사용하는 것이 좋습니다.",
    "A shell containing smaller shells. The smaller shells are shot outwards\nand each explode their own loads.": "작은 자탄을 품은 폭죽입니다. 자탄이 바깥쪽으로 발사된 뒤\n각각 지정된 효과 묶음을 폭발시킵니다.",
    "A shell must have a selected launch site.": "폭죽탄에는 발사 지점을 선택해야 합니다.",
    "A shell must have a selected load.": "폭죽탄에는 주 효과 묶음을 선택해야 합니다.",
    "A shell NEEDS a load, as what are you even firing otherwise. The main load\ncan be selected with the button, and be chosen from the loads you've\npreviously defined.\n\n": "폭죽탄에는 반드시 주 효과 묶음이 필요합니다.\n버튼을 눌러 앞에서 저장한 효과 묶음 중 하나를 선택하세요.",
    "A shell needs to be assigned to a launch site, from where it will be fired.\n\nAt the bottom of the left panel you will find several settings that\ndetermine how the shell is fired.\n\n": "폭죽탄에는 발사될 발사 지점을 지정해야 합니다.\n왼쪽 패널 아래에서 폭죽탄의 발사 방식을 설정할 수 있습니다.",
    "A shell of shells effect can use at most 4 custom loads.": "자탄 폭발 효과에는 사용자 효과 묶음을 최대 4개까지 사용할 수 있습니다.",
    "A short burst of crackling particles popping in and out.": "타닥거리는 입자가 짧게 나타났다 사라지는 효과입니다.",
    "A show is basically a recurring sequence, where you set the schedule to\ncertain days of the year, or repeating it monthly, weekly (or even daily?),\nor simply every so many minutes.\n\n": "공연은 일정에 따라 반복되는 시퀀스입니다. 특정 날짜나 매월, 매년,\n매일 또는 일정한 실시간 분 간격으로 실행할 수 있습니다.",
    "A simple burst of particles from the burst point, without any of\nthe colour pattern or shaping options found on the more elaborate\nburst effects.\n": "폭발 지점에서 입자가 단순하게 퍼집니다.\n복잡한 폭발 효과에 있는 색상 패턴이나 모양 설정은 없습니다.\n",
    "A single comet is launched from a point.": "한 지점에서 혜성 하나를 발사합니다.",
    "A sphere with colours arranged in layers\n according to the sequence": "색상 시퀀스에 따라 층으로 배치된\n구형 폭발",
    "A star with an innard of one colour\nand an outer layer of another colour": "안쪽과 바깥층의 색상이 서로 다른 별",
    "A star with colours arranged in a gumball\npattern according to the sequence": "색상 시퀀스에 따라 검볼 패턴으로\n색을 배치한 별",
    "A star with colours arranged in layers\n according to the sequence": "색상 시퀀스에 따라 층으로\n색을 배치한 별",
    "A star with three inside-outside\nlayers of colours, like a gumball": "검볼처럼 안팎으로 세 색상 층을 가진 별",
    "A symmetrical sphere of particles.\n": "입자가 대칭적인 구 모양으로 퍼집니다.\n",
    "A symmetrical star with spikes of particles coming from a middle point.\n": "중심점에서 입자 살이 뻗는 대칭적인 별 모양입니다.\n",
    "A tiny burst of a handfull of particles suitable as secondary 'pop',\nor for small scale fireworks.": "적은 수의 입자가 작게 터집니다. 보조 폭발이나\n소규모 불꽃에 적합합니다.",
    "A wisp-like effect rises slowly from the ground, leaving a short cone of particles.\nThe wisp flies up and slows down repeatedly as it wanders away.": "도깨비불 같은 효과가 짧은 원뿔형 입자를 남기며 지면에서 천천히 상승합니다.\n흔들리며 멀어지는 동안 상승과 감속을 반복합니다.",
    "About 1 minute, or 5 in game days before a show starts, a news message will\nappear, and another one as the show begins. Their messages are customizable,\nhow fun! Leaving them empty will skip them.\n\n": "공연 시작 약 1분 전(게임 내 5일 전)과 시작 시점에 뉴스 메시지를\n표시할 수 있습니다. 문구는 직접 설정하며 비워 두면 표시하지 않습니다.",
    "Add": "추가",
    "Add Ascend Load to Shell": "폭죽탄에 상승 효과 추가",
    "Add Ascend Loads": "상승 효과 추가",
    "Add at": "지정 시간에 추가",
    "Add Effect": "효과 추가",
    "Add Phase": "단계 추가",
    "Add Sequence": "시퀀스 추가",
    "Additional persistence in ticks": "추가 지속 시간(틱)",
    "Additional persistence in ticks before\nsub shells explode": "자탄이 폭발하기 전 추가 지속 시간(틱)",
    "Adds a crackling spark effect to the fountain": "분수에 타닥거리는 불꽃 효과를 추가합니다.",
    "Affects number of comets": "혜성 수에 영향을 줍니다.",
    "Affects number of particles": "입자 수에 영향을 줍니다.",
    "Affects number of particles of sub shells": "자탄의 입자 수에 영향을 줍니다.",
    "Affects physical size of sub shells": "자탄의 물리 크기에 영향을 줍니다.",
    "Affects the height that the particles reach": "입자가 도달하는 높이에 영향을 줍니다.",
    "Affects the number of particles": "입자 수에 영향을 줍니다.",
    "Affects the speed at which the parciles\nfly off, and inversely affects their lifetime.": "입자가 튀어나가는 속도에 영향을 주며,\n수명에는 반대로 작용합니다.",
    "Amount": "수량",
    "Angular Size": "분사각",
    "Annual dates": "연간 날짜",
    "April": "4월",
    "ascend load": "상승 효과 묶음",
    "Ascend Loads": "상승 효과",
    "Attempted Fireworks Lit is the number of shells and\nground effects set off.": "실행 시도 불꽃은 실행된 폭죽탄과\n지상 효과의 수입니다.",
    "Attempted Particles is number of particles that have\nbeen attemped to make.": "생성 시도 입자는 만들려고 시도한\n입자의 총수입니다.",
    "August": "8월",
    "Azimuth": "방위각",
    "Azimuth (0=Y, 90=X)": "방위각(0=Y, 90=X)",
    "Base Colour": "기본 색상",
    "Before we begin, one word of advice, be aware that a proper fireworks show\ntakes a lot of time and patience to set up correctly, and also that the results\nare well worth the wait!\n\nSee you in the next tab!": "제대로 된 불꽃놀이 공연을 만들려면 많은 시간과 인내가 필요하지만,\n완성된 결과는 그만한 가치가 있습니다!\n다음 탭에서 시작해 봅시다.",
    "Before you can start creating fireworks, you will need to set up the launch\nsites in the park.\n\nLaunch sites are the locations from which you can fire the fireworks,\nthink of them as the big cardboard boxes with tubes that you might have\n": "불꽃을 만들기 전에 공원에 발사 지점을 설정해야 합니다.\n발사 지점은 불꽃이 발사되는 위치입니다. 실제 불꽃놀이에서 보는\n여러 발사관이 든 큰 상자와 비슷하다고 생각하면 됩니다.",
    "Beware of adding too many, or too large effects to a load as there's a hard\ncap of 3200 misc entities in the park, which includes things besides\nfireworks, such as balloons and money effects.\n\n": "효과를 너무 많이 넣거나 지나치게 크게 만들지 마세요. 공원의 기타 개체는\n풍선과 돈 효과 등을 포함해 최대 3200개로 제한됩니다.",
    "Big head type": "큰 머리 형태",
    "Built with openrct2-flexui": "openrct2-flexui로 제작",
    "button that opens window listing the current number of particles and various\nother useful stats.\nAnother useful thing to know is untracked particles with the invisible colour\nwill not be spawned at all, to save the budget.\n\nYou can remove unwanted effects with the delete mode, which works similar \nto the 'quick fire staff'.": "버튼이 있으며 현재 입자 수와 유용한 통계를 보여 줍니다.\n보이지 않는 색상의 추적되지 않는 입자는 한도를 아끼기 위해 생성되지 않습니다.\n필요 없는 효과는 직원 빠른 해고와 비슷하게 작동하는\n삭제 모드로 제거할 수 있습니다.",
    "By default shells fire straight up but you can choose to fire them at an\nangle using Tilt and Azimuth. Tilt is the angle from straight up (0) to 45\ndegrees diagonally up, and azimuth is the direction in which the shell will\nbe fired in degrees.\n\n": "기본적으로 폭죽탄은 수직으로 발사됩니다. 기울기와 방위각으로 각도를 바꿀 수\n있습니다. 기울기는 수직(0)에서 대각선 위쪽(45도)까지이며,\n방위각은 지도상 발사 방향을 각도로 정합니다.",
    "Cancel": "취소",
    "Christmas": "크리스마스",
    "Clear": "지우기",
    "Click a load to add it.": "추가할 효과 묶음을 클릭하세요.",
    "Clone": "복제",
    "Close": "닫기",
    "Colour": "색상",
    "Colour 1": "색상 1",
    "Colour 1-3": "색상 1~3",
    "Colour 1A": "색상 1A",
    "Colour 1B": "색상 1B",
    "Colour 1C": "색상 1C",
    "Colour 2": "색상 2",
    "Colour 2A": "색상 2A",
    "Colour 2B": "색상 2B",
    "Colour 2C": "색상 2C",
    "Colour 3": "색상 3",
    "Colour 4": "색상 4",
    "Colour 5": "색상 5",
    "Colour 6": "색상 6",
    "Colour for the crackle": "타닥불꽃 색상",
    "Colour of the comet's head": "혜성 머리 색상",
    "Colour of the comets' heads": "혜성 머리의 색상",
    "Colour of the particles": "입자 색상",
    "Colour of the the launched subshells": "발사되는 자탄의 색상",
    "Colour of the trails the fish leave behind": "날치가 남기는 꼬리의 색상",
    "Colour one of the trail": "꼬리의 첫 번째 색상",
    "Colour pattern": "색상 패턴",
    "Colour Pattern": "색상 패턴",
    "Colour Sequence": "색상 시퀀스",
    "Colour Sequence Editor": "색상 시퀀스 편집기",
    "Colour Sequences": "색상 시퀀스",
    "Colour two of the trail": "꼬리의 두 번째 색상",
    "Colours": "색상",
    "Colours for the particles": "입자에 사용할 색상",
    "Colours of the comet's trail": "혜성 꼬리 색상",
    "Colours of the comets' trails": "혜성 꼬리의 색상",
    "Colours of the particles": "입자 색상",
    "Comet Bursts Crackle": "혜성 끝 타닥불꽃",
    "Comet Fan": "부채꼴 혜성",
    "Comet Fan Effect": "부채꼴 혜성 효과",
    "Comet Head Big": "큰 혜성 머리",
    "Comet Mine": "혜성 분사",
    "Comet Mine Effect": "혜성 분사 효과",
    "Comet Trail": "혜성 꼬리",
    "Comet Trail Density": "혜성 꼬리 밀도",
    "Comet Trail Width": "혜성 꼬리 폭",
    "Comets alternate in colour for stripes": "혜성 색상을 번갈아 사용해 줄무늬 생성",
    "Comets Burst At End": "혜성 끝에서 폭발",
    "Comets Burst Crackle": "혜성 끝 타닥불꽃",
    "Conflicts": "충돌 수",
    "Congrats on making it all the way here! Unless you skipped, that is, then\nyou need to go back!\n\nThe hard work is done. A show is basically a sequence with some extra bells\nand whistles.\n\n": "여기까지 왔다면 축하합니다! 중간을 건너뛰었다면 다시 돌아가 보세요.\n어려운 작업은 끝났습니다. 공연은 기본적으로 시퀀스에\n몇 가지 추가 기능을 더한 것입니다.",
    "Controls the density of the comet trails": "혜성 꼬리의 밀도를 조절합니다.",
    "Controls the width of the comet trails": "혜성 꼬리의 폭을 조절합니다.",
    "Coordinates": "좌표",
    "Count": "수량",
    "Crackle": "타닥불꽃",
    "Crackle A": "타닥불꽃 A",
    "Crackle B": "타닥불꽃 B",
    "Crackle Colour": "타닥불꽃 색상",
    "Crackle Effect": "타닥불꽃 효과",
    "Created by: {BABYBLUE}": "제작: {BABYBLUE}",
    "Current Ground Effect": "현재 지상 효과",
    "Current Load": "현재 효과 묶음",
    "Current Sequence": "현재 시퀀스",
    "Current Shell": "현재 폭죽탄",
    "Current Show": "현재 공연",
    "Current site": "현재 발사 지점",
    "Current unsaved editor state": "현재 저장되지 않은 편집 상태",
    "Custom Loads": "사용자 효과 묶음",
    "Daily": "매일",
    "Day": "일",
    "Day of month:": "날짜:",
    "Define the colours from left to right, pick a name, and be sure to set the\nnumber correctly.\n\nOn the right you will find several buttons. You may delete all defined data,\nwhich does exactly what it says.\n\n": "왼쪽부터 색상을 정하고 이름과 색상 수를 정확히 설정하세요.\n오른쪽에는 여러 관리 버튼이 있습니다.\n'모든 데이터 삭제'는 저장된 불꽃 데이터를 전부 지웁니다.",
    "Defined Ground Effects": "저장된 지상 효과",
    "Defined Launch Sites": "저장된 발사 지점",
    "Defined Loads": "저장된 효과 묶음",
    "Defined Sequences": "저장된 시퀀스",
    "Defined Shells": "저장된 폭죽탄",
    "Defined Shows": "저장된 공연",
    "Delay": "지연",
    "Delayed Fireworks is the number of shells that were\n delayed a tick due to the limit being hit.": "지연된 불꽃은 한도 때문에 1틱씩\n지연된 폭죽탄 수입니다.",
    "Delete": "삭제",
    "Delete All Data": "모든 데이터 삭제",
    "Delete Mode: {RED}ON": "삭제 모드: {RED}켜짐",
    "Delete Mode: OFF": "삭제 모드: 꺼짐",
    "Delete Sequence": "시퀀스 삭제",
    "Deletes the selected phase.": "선택한 단계를 삭제합니다.",
    "Density": "밀도",
    "Determines the sequence and arrangement\nof colours": "색상의 순서와 배치를 결정합니다.",
    "Download: ": "다운로드: ",
    "Duplicates the selected phase and inserts\nit right after.": "선택한 단계를 복제해 바로 뒤에 삽입합니다.",
    "Duration": "지속 시간",
    "Duration (secs)": "지속 시간(초)",
    "Each comet ends in a crackle": "각 혜성이 끝날 때 타닥불꽃이 납니다.",
    "Edit": "편집",
    "Effect": "효과",
    "Effects": "효과",
    "Enable at least one show with a trigger to start the programme.": "실행 조건이 설정된 공연을 하나 이상 활성화해야 합니다.",
    "end": "끝",
    "End of sequence": "시퀀스 종료",
    "Entity": "개체",
    "Entity: ": "개체: ",
    "Entity: none": "개체: 없음",
    "Every": "매",
    "Every day": "매일",
    "Everything is saved in the park file and can be shared with anyone who also\nhas the plugin. You can also open the parks without plugin safely but the\nfireworks will not work then of course.": "모든 내용은 공원 파일에 저장되므로 같은 플러그인을 가진 사람과\n공유할 수 있습니다. 플러그인 없이도 공원은 안전하게 열리지만\n불꽃놀이는 작동하지 않습니다.",
    "Exact number of comets to make the fan": "부채꼴을 이루는 정확한 혜성 수",
    "Exact number of particles": "정확한 입자 수",
    "Exact number of particles per spray": "분사 하나당 정확한 입자 수",
    "Exact number of sub shells": "자탄의 정확한 개수",
    "Existing exports:": "저장된 내보내기 항목:",
    "Expand Sub-Sequences": "하위 시퀀스 펼치기",
    "Export Data": "데이터 내보내기",
    "Export Fireworks Data": "불꽃놀이 데이터 내보내기",
    "Extra Longevity": "추가 지속 시간",
    "Fan Angle": "부채꼴 각도",
    "Fan is one colour": "부채꼴 전체에 한 색상 사용",
    "Fan Orientation": "부채꼴 방향",
    "Fire": "불꽃",
    "Fire next item after:": "다음 항목 실행 기준:",
    "Fireworks": "불꽃놀이",
    "Fireworks - Editor": "불꽃놀이 - 편집기",
    "Fireworks - Playing Show Programme": "불꽃놀이 - 공연 프로그램 재생 중",
    "Fireworks - Tutorial": "불꽃놀이 - 사용법",
    "Fireworks Debugger": "불꽃놀이 디버거",
    "Fireworks Debugger Info": "불꽃놀이 디버거 설명",
    "Flying Fish": "날치 효과",
    "Flying Fish Effect": "날치 효과 편집",
    "Forest": "숲",
    "Fountain": "분수",
    "Fountain Effect": "분수 효과",
    "Fountain Phase": "분수 단계",
    "functionality. \nHandily enough, the tabs are in the order that you will likely want to use them,\nso you can follow along with the tutorial as you explore the plugin.\n\n": "탭은 보통 작업하는 순서대로 배치되어 있습니다.\n플러그인을 살펴보며 이 안내서를 순서대로 따라가면 됩니다.",
    "G.E.": "지상",
    "G.E. ": "지상 효과 ",
    "Gives each particle in the ring a trailing streak": "고리의 각 입자에 꼬리를 추가합니다.",
    "Gives the comets a larger cluster head\ninstead of a single particle": "혜성 머리를 단일 입자 대신\n큰 입자 무리로 표시합니다.",
    "Ground Effect": "지상 효과",
    "Ground effect tab (unsaved ground effect)": "지상 효과 탭(저장되지 않음)",
    "Ground Effects": "지상 효과",
    "Ground Effects Editor": "지상 효과 편집기",
    "GroundEffect": "지상 효과",
    "Head": "머리",
    "Head A": "머리 A",
    "Head B": "머리 B",
    "Heads": "머리",
    "Height": "높이",
    "Hide": "접기",
    "How densely clustered the spray is\nlongitudinally.": "분사 입자가 수직 방향으로\n얼마나 밀집되는지 정합니다.",
    "Icon": "아이콘",
    "Icons": "아이콘",
    "If the index field is left empty, it will simply take the last item of the list.\nThe time fields both work with the format of '2m30s20t', two minutes,\n30 seconds, 20 ticks, or any combination of those.\nYou could just say '60 ticks' for 1.5 seconds,'1m' for 1 minute for example,\nor simply '0' to fire it simultaneously with the previous.": "번호 입력란을 비우면 목록의 마지막 항목을 기준으로 합니다.\n시간은 '2m30s20t'(2분 30초 20틱)처럼 조합해 입력할 수 있습니다.\n예를 들어 1.5초는 '60t', 1분은 '1m', 이전 항목과 동시에 실행하려면\n'0'을 입력하세요.",
    "If you accidentally clicked an entity or no longer wish it to be linked,\nthe unfollow button will detach the launch site from the entity. When you\ndo follow an entity, the coordinates can be set to be relative to the entity,\nsuch as '20 units above'.": "개체를 잘못 선택했거나 연결을 해제하려면 '연결 해제'를 누르세요.\n개체를 따라가도록 설정한 경우 좌표는 개체 기준 상대 위치가 됩니다.\n예를 들어 개체보다 20단위 위로 설정할 수 있습니다.",
    "If you do not click on an entity, the location will be set to the middle of\nthe tile at the land surface height. You can use the XYZ spinners and arrow\nbuttons to fine tune the location.\n\n": "개체가 아닌 곳을 누르면 해당 타일 중앙의 지면 높이에 설정됩니다.\nXYZ 입력란과 화살표 버튼으로 위치를 세밀하게 조정할 수 있습니다.",
    "If you lock the delay, since the last item was at 12s, and had a delay\nof 2 seconds, it will see that there's now the new item at 11 seconds,\nand so a delay of 2 seconds from there will shift the time to 13 seconds.\nHad you added it with the lock on time, the item would have stayed at\n12 seconds, and had its delay updated to 1 second.": "지연을 고정하면 기존 12초 항목의 2초 지연을 유지하므로,\n11초에 삽입된 항목을 기준으로 13초로 이동합니다.\n시간을 고정했다면 기존 항목은 12초에 남고 지연만 1초로 바뀝니다.",
    "Ignores azimuth and tilt, using a random\norientation each time the effect fires": "방위각과 기울기를 무시하고 효과가 실행될 때마다\n무작위 방향을 사용합니다.",
    "Ignores azimuth and tilt, using a random\norientation each time the ring fires": "방위각과 기울기를 무시하고 고리가 실행될 때마다\n무작위 방향을 사용합니다.",
    "Imminent": "곧 시작",
    "Import Data": "데이터 가져오기",
    "Import Fireworks Data": "불꽃놀이 데이터 가져오기",
    "In the shells tab it's time to actually launch a load from a launch site,\nhow exciting!\n\nYou know the drill by now, left is the editor, right is the list, and give\nyour shells proper names!\n\n": "폭죽탄 탭에서는 발사 지점에서 효과 묶음을 실제로 쏘아 올립니다.\n왼쪽은 편집기, 오른쪽은 목록입니다. 폭죽탄에도 알맞은 이름을 붙이세요!",
    "In-game annual dates": "게임 내 연간 날짜",
    "In-game recurring": "게임 내 반복",
    "Index": "번호",
    "Invalid ascend load": "잘못된 상승 효과",
    "Invalid custom loads": "잘못된 사용자 효과 묶음",
    "Invalid delay": "잘못된 지연 시간",
    "Invalid effect": "잘못된 효과",
    "Invalid entry": "잘못된 항목",
    "Invalid ground effect": "잘못된 지상 효과",
    "Invalid load": "잘못된 효과 묶음",
    "Invalid selection": "잘못된 선택",
    "Invalid sequence": "잘못된 시퀀스",
    "Invalid shell": "잘못된 폭죽탄",
    "Invalid show": "잘못된 공연",
    "Invalid show configuration": "잘못된 공연 설정",
    "Invalid time": "잘못된 시간",
    "Invalid trigger": "잘못된 실행 조건",
    "It's always possible to add items to fire during a sub-sequence through the\n'add at' button however. If sub sequence was set to be 'next after end', and you\ninsert something in the middle, essentially you get a negative delay time.\nAs this would look confusing, it will instead say 0. \n\n": "'지정 시간에 추가'로 하위 시퀀스 실행 중간에도 항목을 넣을 수 있습니다.\n하위 시퀀스가 '종료 뒤'로 설정된 상태에서 중간에 항목을 넣으면\n계산상 음수 지연이 되므로 혼동을 막기 위해 0으로 표시합니다.",
    "It's possible for the shell to leave a trail, the colours of which can be\nchosen as well as how thick and dense it is. The colour of the shell itself\ncan be chosen, too.": "폭죽탄에 꼬리를 남기고 색상, 굵기, 밀도를 정할 수 있습니다.\n폭죽탄 자체의 색상도 선택할 수 있습니다.",
    "Item": "항목",
    "Item In Use": "사용 중인 항목",
    "Items": "항목",
    "its max height before falling back down, basically it's the launch speed,\nwhile delay is how long until the main load is set off.\nThe random value will randomly adjust the trajectory params by a percentage.\nThere are some preset buttons to give a quick preset for the launch params,\nthey do not affect the loads.": "즉 사실상 발사 속도이며, 지연은 주 효과 묶음이 실행될 때까지의 시간입니다.\n무작위 편차는 궤도 값을 일정 비율만큼 무작위로 조정합니다.\n프리셋 버튼으로 발사 값을 빠르게 설정할 수 있으며\n효과 묶음에는 영향을 주지 않습니다.",
    "July": "7월",
    "June": "6월",
    "Keep existing": "기존 항목 유지",
    "Keep new": "새 항목 유지",
    "Keep that in mind when creating your loads, and fireworks in general as it's\nvery easy to hit that limit.\n\nTo help keep track of what the firework is doing, the plugin has a debug\n": "효과 묶음과 불꽃을 만들 때 이 한도를 기억하세요. 쉽게 한도에 도달합니다.\n불꽃의 상태를 확인할 수 있도록 플러그인에는 디버거",
    "Large Simple Fountain": "대형 단순 분수",
    "last": "마지막",
    "Lastly there's a button to fully expand or collapse the sequence tree.\nIt's possible but not recommended to edit in the expanded view, but it can be\nuseful to get a better grasp on what sequences in sequences in sequences in..\nlook like when in the actual show.": "마지막 버튼으로 시퀀스 트리를 모두 펼치거나 접을 수 있습니다.\n펼친 상태에서도 편집할 수 있지만 권장하지 않습니다. 대신 여러 단계로\n중첩된 시퀀스가 실제 공연에서 어떻게 구성되는지 파악할 때 유용합니다.",
    "Lastly there's the tutorial button, which opens the very window you're\ncurrently reading. You can always open it up again for some help!": "마지막 '사용법 열기' 버튼으로 현재 보고 있는 안내 창을 다시 열 수 있습니다.\n도움이 필요할 때 언제든 확인하세요!",
    "Lastly, the shell will be given a height, and delay. In most cases these\nshould be the same, (the sync check keeps them in sync), but you may choose\nto separate them. Height is how many game ticks it takes the shell to reach\n": "마지막으로 높이와 지연을 설정합니다. 보통 두 값은 같아야 하며\n'동기화'를 켜면 함께 바뀝니다. 필요하면 따로 설정할 수도 있습니다.\n높이는 폭죽탄이 정점에 도달하는 데 걸리는 게임 틱 수입니다.",
    "Launch Site": "발사 지점",
    "Launch Sites": "발사 지점",
    "Length": "길이",
    "Lets the comets pop into a small burst\nat the end": "혜성이 끝에서 작게 폭발하도록 합니다.",
    "Load": "효과 묶음",
    "Load ": "효과 묶음 ",
    "Load Editor": "효과 묶음 편집기",
    "Load tab (unsaved load, Shell of Shells sub-load)": "효과 묶음 탭(저장되지 않은 자탄용 하위 묶음)",
    "Load tab (unsaved load)": "효과 묶음 탭(저장되지 않음)",
    "Loads": "효과 묶음",
    "Location for news message locator: ": "뉴스 메시지 표시 위치: ",
    "Lock:": "고정:",
    "main load": "주 효과 묶음",
    "Main Load: ": "주 효과 묶음: ",
    "March": "3월",
    "Max Height": "최대 높이",
    "May": "5월",
    "Micro Burst": "소형 폭발",
    "Micro Burst Effect": "소형 폭발 효과",
    "MiscEntityCount is current number of all other\nmisc entities. Total particle budget is 3200.": "기타 엔티티 수는 그 밖의 모든 기타 개체 수입니다.\n전체 입자 한도는 3200입니다.",
    "Month": "월",
    "Month:": "월:",
    "Monthly": "매월",
    "Moves the selected phase 1 postion up.": "선택한 단계를 한 칸 위로 이동합니다.",
    "Much like the launch sites tab, the left panel is where you can define a new\nload, while the right panel shows the list of already defined loads, with an\nadditional search-field now as this list is likely to grow large. Once again,\n": "발사 지점 탭과 마찬가지로 왼쪽에서 새 효과 묶음을 만들고,\n오른쪽에서 저장된 목록을 봅니다. 목록이 길어질 수 있어\n검색 입력란도 제공됩니다.",
    "Multiple Spray Mines combine to form a fan.": "여러 입자 분사를 결합해 부채꼴을 만듭니다.",
    "Name": "이름",
    "Name / Detail": "이름 / 세부 정보",
    "Name Conflicts": "이름 충돌",
    "Netherlands": "네덜란드",
    "New": "새로 만들기",
    "Newer Fireworks Plugin Version": "불꽃놀이 플러그인 새 버전 알림",
    "News announcement ~1 min before show (disabled if empty):": "공연 약 1분 전 뉴스 알림(비워 두면 사용 안 함):",
    "News announcement at start of show (disabled if empty):": "공연 시작 뉴스 알림(비워 두면 사용 안 함):",
    "No": "아니요",
    "No additional information is available for this effect yet.": "이 효과에 대한 추가 설명이 아직 없습니다.",
    "No enabled shows": "활성화된 공연 없음",
    "No sequence": "시퀀스 없음",
    "No sequence assigned": "시퀀스가 지정되지 않았습니다.",
    "Normally when a sequence fails to launch a shell due to the particle limit\nhaving been hit, it will delay the shell a frame, until it can be fired\nagain. This interruption would break the music syncronisation, so for a\n": "입자 한도 때문에 폭죽탄을 발사하지 못하면 보통 발사 가능할 때까지\n한 프레임씩 지연합니다. 이 지연은 음악 동기화를 흐트러뜨릴 수 있으므로\n공연에서는 다른 방식을 선택할 수 있습니다.",
    "Now the fun begins! This is where you can define the loads for in shells,\nwhich will likely be the bulk of your show.\nA load is a collection of effects that will be fired upwards together in a shell,\nto create more complex effects in the sky.\n\n": "이제 효과 묶음을 만들 차례입니다. 공연의 대부분을 구성하는 부분입니다.\n효과 묶음은 하나의 폭죽탄에서 함께 발사되는 효과 모음으로,\n하늘에 더 복잡한 형태를 만들어 냅니다.",
    "Number Comets": "혜성 수",
    "Number of particles per spike": "별살 하나당 입자 수",
    "Number of seconds this phase lasts.": "이 단계가 지속되는 시간(초)입니다.",
    "Number of sprays to form the fan": "부채꼴을 이루는 분사 수",
    "Number of ticks of delay before the\neffect starts": "효과가 시작되기 전 지연 시간(틱)",
    "Number Sprays": "분사 수",
    "Ocean": "바다",
    "October": "10월",
    "Offset from entity": "개체 기준 오프셋",
    "Okay": "확인",
    "Once you're ready to start your show(s) select them one by one in the list,\nand enabled them with the 'Selected Show: Disabled/Enabled' button.\nA green Y will appear next to the show indicating it is enabled.\nThen all that's left is to press the big 'Start Show Programme' button.\nDoing this will close the editor and instead open the show-playing window,\n": "공연 준비가 끝나면 목록에서 하나씩 선택해 활성/비활성 버튼으로 켜세요.\n활성화된 공연 옆에는 초록색 '예'가 표시됩니다.\n그다음 큰 '공연 프로그램 시작' 버튼을 누르면 편집기가 닫히고\n공연 재생 창이 열립니다.",
    "One colour for the fish": "날치에 한 색상 사용",
    "One final time, the left panel is the editor, and right the list of shows,\nand whether they're active.\nThe show needs a sequence, the master-sequence if you will.\n\n": "마지막으로 왼쪽 패널은 편집기, 오른쪽은 공연 목록과 활성 상태입니다.\n공연에는 전체를 지휘할 주 시퀀스가 필요합니다.",
    "One set of colours for comets fired up,\nand one for the ones down": "위로 발사되는 혜성과 아래쪽 혜성에\n서로 다른 색상 조합 사용",
    "One set of colours for the comets": "모든 혜성에 한 색상 조합 사용",
    "Open Tutorial": "사용법 열기",
    "Opens the window to add a new phase at\nthe end.": "마지막에 새 단계를 추가하는 창을 엽니다.",
    "Opens the window to edit the selected phase.": "선택한 단계를 편집하는 창을 엽니다.",
    "Orientation of the effect in the horizontal plane": "효과의 수평 방향",
    "Orientation of the effect in the vertical plane": "효과의 수직 방향",
    "Orientation of the ring in the horizontal plane": "고리의 수평 방향",
    "Orientation of the ring in the vertical plane": "고리의 수직 방향",
    "Other Settings": "기타 설정",
    "Palette Options": "팔레트 설정",
    "Palm": "야자수형 폭발",
    "Palm Effect": "야자수형 폭발 효과",
    "ParticleCount is current number of crashed vehicle\nparticles. This excludes other particle types.\nTotal particle budget is 3200.": "입자 수는 현재 충돌 차량 입자 수입니다.\n다른 종류의 입자는 포함하지 않습니다.\n전체 입자 한도는 3200입니다.",
    "Percentage for how much the wisp will\nstray off going up perfectly vertical.": "불꽃이 완전한 수직 상승 경로에서\n벗어나는 정도(%)",
    "Period:": "주기:",
    "Phases": "단계",
    "Physical Size": "물리 크기",
    "Physical size of effect, affects duration\nof the effect": "효과의 물리 크기이며 지속 시간에도\n영향을 줍니다.",
    "Physical size of the effect.": "효과의 물리 크기입니다.",
    "Physical Size over which sub shells are\nlaunched": "자탄이 흩어져 발사되는 물리 범위",
    "Pick on map": "지도에서 선택",
    "Pict": "단순 폭발",
    "Pict Effect": "단순 폭발 효과",
    "Play from index": "선택 항목부터 재생",
    "Play from start": "처음부터 재생",
    "Playing": "재생 중",
    "Preset": "프리셋",
    "Rainbow": "무지개",
    "RainbowLong": "긴 무지개",
    "Random Angle": "무작위 방향",
    "Randomness": "무작위 편차",
    "real minutes": "실시간 분마다",
    "Real-time": "실시간",
    "Real-time interval": "실시간 간격",
    "Recurring": "반복",
    "remember to name your items for your own sake!\n\nWith the add-effect dropdown you can add various effects to the load. Each\nwill spawn their own window with shape, size and colour settings for that\nspecific effect. Each effect window has a '?' button for explanations.\n\n": "항목에는 꼭 알아보기 쉬운 이름을 붙이세요!\n'효과 추가' 목록에서 다양한 효과를 묶음에 넣을 수 있습니다.\n각 효과 창에서 모양, 크기, 색상을 설정하며 '?' 버튼으로 설명을 봅니다.",
    "Retry misfires due to particle limits and delay sequence": "입자 제한으로 실패하면 재시도하고 시퀀스 지연",
    "Ring": "고리형 폭발",
    "Ring Effect": "고리형 폭발 효과",
    "Same as Last": "마지막 항목과 동일",
    "Save current data as:": "현재 데이터를 다음 이름으로 저장:",
    "Say you already have a short list of items, and the last item is at 10s.\nNow you add an item 2s after the last, it will naturally be at 12s.\nNow say you add another item AT 11s afterwards.\nNow the behaviour of the lock will become important, as it determines\nwhether the time values, or the delay values are kept true.": "마지막 항목이 10초인 목록에서 그 항목 2초 뒤에 새 항목을 추가하면\n새 항목은 12초에 놓입니다. 이후 11초 위치에 또 다른 항목을 넣는 경우,\n고정 설정에 따라 절대 시간과 지연 시간 중 어느 값을 유지할지가 결정됩니다.",
    "Schedule": "일정",
    "Search by prefix": "이름 앞부분으로 검색",
    "seen on New Year's Eve and other similar celebrations.\n\nOn the left panel you can see the options to define a new launch site while\nthe panel on the right shows the list of already defined launch sites.\n\n": "왼쪽 패널에서는 새 발사 지점을 설정하고,\n오른쪽 패널에서는 저장된 발사 지점 목록을 확인합니다.",
    "Select a row in the sequence list to play from.": "재생을 시작할 항목을 시퀀스 목록에서 선택하세요.",
    "Select a shell, ground effect, or sequence before adding.": "추가하기 전에 폭죽탄, 지상 효과 또는 시퀀스를 선택하세요.",
    "Select an export to import:": "가져올 내보내기 항목 선택:",
    "Select Custom Load": "사용자 효과 묶음 선택",
    "Select Ground Effect for Sequence": "시퀀스에 넣을 지상 효과 선택",
    "Select Load For Shell": "폭죽탄용 효과 묶음 선택",
    "Select Location": "위치 선택",
    "Select Main Load": "주 효과 묶음 선택",
    "Select News Message Position": "뉴스 메시지 위치 선택",
    "Select preset": "프리셋 선택",
    "Select Sequence": "시퀀스 선택",
    "Select Sequence For Sequence": "시퀀스에 넣을 시퀀스 선택",
    "Select Sequence for Show": "공연용 시퀀스 선택",
    "Select Shell for Sequence": "시퀀스에 넣을 폭죽탄 선택",
    "Select up to four of your own saved loads.\nYou cannot select loads with 'shell-of-shells'\neffects as subshells themselves.": "저장한 효과 묶음을 최대 4개까지 선택합니다.\n자탄 폭발 효과가 들어간 묶음은\n다시 자탄으로 선택할 수 없습니다.",
    "Selected load no longer exists.": "선택한 효과 묶음이 더 이상 존재하지 않습니다.",
    "Selected sequence": "선택한 시퀀스",
    "Selected show {GREEN}ENABLED": "선택한 공연 {GREEN}활성",
    "Selected show {GREY}N/A": "선택한 공연 {GREY}해당 없음",
    "Selected show {RED}DISABLED": "선택한 공연 {RED}비활성",
    "Selected: ": "선택됨: ",
    "Selected: none": "선택됨: 없음",
    "September": "9월",
    "Seq.": "시퀀스",
    "Sequence": "시퀀스",
    "Sequence ": "시퀀스 ",
    "Sequence Editor": "시퀀스 편집기",
    "Sequence Entry": "시퀀스 항목",
    "Sequence tab (unsaved sequence)": "시퀀스 탭(저장되지 않음)",
    "Sequence: ": "시퀀스: ",
    "Sequences": "시퀀스",
    "Sequences are the very core of this plugin.\n\nThe basic concept is quite easy, it's just a list of shells and ground effects\nto be lit at a certain time\nHowever, sequences can also contain other sequences to build up parts of\nyour show, and reuse certain combinations more easily.\n\n": "시퀀스는 이 플러그인의 핵심입니다.\n기본적으로 정해진 시간에 실행할 폭죽탄과 지상 효과의 목록입니다.\n다른 시퀀스를 포함시켜 공연 일부를 구성하거나\n특정 조합을 손쉽게 재사용할 수도 있습니다.",
    "Set Schedule Trigger": "공연 실행 조건 설정",
    "Set Trigger": "실행 조건 설정",
    "Settings": "설정",
    "Shell": "폭죽탄",
    "Shell ": "폭죽탄 ",
    "Shell Editor": "폭죽탄 편집기",
    "Shell of Shells": "자탄 폭발",
    "Shell of Shells Effect": "자탄 폭발 효과",
    "Shell of Shells sub-load": "자탄용 하위 효과 묶음",
    "Shell tab (unsaved shell)": "폭죽탄 탭(저장되지 않음)",
    "Shells": "폭죽탄",
    "Show": "공연",
    "Show ": "공연 ",
    "Show Editor": "공연 편집기",
    "Show tab (unsaved show)": "공연 탭(저장되지 않음)",
    "show you can choose to instead skip failed effects entirely. Of course,\nit's best to design  your show to not hit the limit to begin with.\n\nTo test the music-sync specifally, you can use the 'Test Show Now' button.\n": "실패한 효과를 완전히 건너뛰도록 설정할 수 있습니다. 물론 처음부터\n입자 한도에 걸리지 않도록 공연을 설계하는 것이 가장 좋습니다.\n음악 동기화는 '공연 시험' 버튼으로 확인하세요.",
    "Shows": "공연",
    "Since ground effects are not fired up, you can add effects directly in a\nground effect and assign a launch site to them. The effects available here\ndiffer from the ones in loads as these ones are suited for lighting on the\nground.\n\n": "지상 효과는 쏘아 올리지 않으므로 효과를 직접 추가하고 발사 지점을\n지정합니다. 여기서 사용할 수 있는 효과는 지상 연출에 맞게 구성되어\n효과 묶음의 효과와 다릅니다.",
    "Since sequences have a duration, when you add one to another sequence, you\ncan choose how the 'add after' button should behave for it.\nA future item can either be added after the very start of the sub-sequence,\nor after the last item of the sub-sequence.\nIn the listview this is indicated with the 'Next After' column.": "시퀀스에는 지속 시간이 있으므로 다른 시퀀스에 넣을 때\n'뒤에 추가'의 기준을 선택할 수 있습니다. 이후 항목을 하위 시퀀스의\n시작 뒤에 놓거나 마지막 항목 뒤에 놓을 수 있으며,\n목록의 '다음 실행 기준' 열에 표시됩니다.",
    "Singular Fish": "개별 날치",
    "Site ": "지점 ",
    "Size": "크기",
    "Skip misfires due to particle limits and keep sync": "입자 제한으로 실패하면 건너뛰고 동기화 유지",
    "Skipped Fireworks is the number of shells that were\n skipped due to the limit being hit.": "건너뛴 불꽃은 한도 때문에\n실행되지 않은 폭죽탄 수입니다.",
    "Skipped Particles is number of particles were attempted\nto spawn but failed due to the limit being hit.": "생성 실패 입자는 한도에 걸려\n만들지 못한 입자 수입니다.",
    "Small shells are represented by a single particle, but for bigger shells you\nmay want to use the 'Big head type' to instead have a small cluster of\nparticle represent the shell.\n\n": "작은 폭죽탄은 단일 입자로 표시됩니다. 큰 폭죽탄에는 '큰 머리 형태'를 켜서\n작은 입자 무리로 표시할 수 있습니다.",
    "Small Simple Fountain": "소형 단순 분수",
    "Some custom palettes can make the editor hard to use.\nUse the default and restore palette buttons to\nmanually easily switch between the default, and the\npark's true palette.": "일부 사용자 팔레트에서는 편집기가 잘 보이지 않을 수 있습니다.\n기본 팔레트와 팔레트 복원 버튼으로\n기본 팔레트와 공원의 원래 팔레트를\n직접 전환할 수 있습니다.",
    "Sort: New-Old": "정렬: 최신순",
    "Sort: Old-New": "정렬: 오래된순",
    "Special Thanks: Basssiiie, Manticore_007, TimmyTuner, In_Error_Predicting_A_Fault": "도움을 주신 분: Basssiiie, Manticore_007, TimmyTuner, In_Error_Predicting_A_Fault",
    "Speed Multiplier": "속도 배율",
    "Sphere": "구형 폭발",
    "Sphere Effect": "구형 폭발 효과",
    "Sphere made of a single type of particle": "한 종류의 입자로 만든 구형 폭발",
    "Spheres of solid colours using Colour 1-6": "색상 1~6을 각각 사용한 단색 구형 폭발",
    "Spheres of two colours mixed using random\ncombinations of Colour 1-6": "색상 1~6 중 두 색을 무작위 조합한\n구형 폭발",
    "Spike Length": "별살 길이",
    "Spray Burst": "분사 폭발",
    "Spray Burst Effect": "분사 폭발 효과",
    "Spray Fan": "부채꼴 분사",
    "Spray Fan Effect": "부채꼴 분사 효과",
    "Spray Mine": "입자 분사",
    "Spray Mine Effect": "입자 분사 효과",
    "Sprays alternate in colour for stripes": "분사 색상을 번갈아 사용해 줄무늬 생성",
    "Sprays of various colours are launced outwards from a central point.\n": "중심점에서 여러 색상의 입자가 바깥쪽으로 분사됩니다.\n",
    "Spring": "봄",
    "Star": "별형 폭발",
    "Star Effect": "별형 폭발 효과",
    "Star made of a single type of particle": "한 종류의 입자로 만든 별형 폭발",
    "Stars of solid colours using Colour 1-6": "색상 1~6을 각각 사용한 단색 별형 폭발",
    "start": "시작",
    "Start of sequence": "시퀀스 시작",
    "Stop and return to editor": "중지하고 편집기로 돌아가기",
    "Sub Shell Density": "자탄 밀도",
    "Sub Shell Size": "자탄 크기",
    "Sub Shells": "자탄 수",
    "Sunset": "노을",
    "Sync": "동기화",
    "Sync with ride music:": "놀이기구 음악과 동기화:",
    "Thank you for downloading the Fireworks plugin by MaxArceus!\n\nThis plugin allows you to create and manage fireworks shows in your park,\nproviding awide range of features and customization options.\n": "MaxArceus의 불꽃놀이 플러그인을 이용해 주셔서 감사합니다!\n이 플러그인으로 공원에서 불꽃놀이 공연을 만들고 관리하며,\n다양한 기능과 세부 설정을 사용할 수 있습니다.",
    "The angle in the horizontal plane of where\nthe particles are shot towards.": "입자가 발사되는 수평 방향입니다.",
    "The angle in the horizontal plane of where\nthe particles are sprayed towards.": "입자가 분사되는 수평 방향입니다.",
    "The angle in the vertical plane of where\nthe particles are shot towards.\n0 = up, 90 = horizontal, 180 = down": "입자가 발사되는 수직 각도입니다.\n0=위, 90=수평, 180=아래",
    "The angle in the vertical plane of where\nthe particles are sprayed towards.\n0 = up, 90 = horizontal, 180 = down": "입자가 분사되는 수직 각도입니다.\n0=위, 90=수평, 180=아래",
    "The angle of the cone of particles.": "입자 원뿔의 각도입니다.",
    "The angle of the fan in a sense of how wide it is": "부채꼴이 퍼지는 너비 각도",
    "The angle of the fan on the ground, which\nway it faces": "지면을 기준으로 부채꼴이 향하는 방향",
    "The Auto Switch Palletes button auto sets the\n palette to the default when the editor is\nopen, and back to the park's true palette during\ntests and when the editor is closed.": "자동 팔레트 전환을 켜면 편집기를 열 때\n기본 팔레트로 바꾸고, 시험 중이거나\n편집기를 닫을 때 공원의 원래 팔레트로\n자동 복원합니다.",
    "The colours of sprays to use in random order": "무작위 순서로 사용할 분사 색상",
    "The editor window is roughly in the centre of the screen and may obscure the effect. Consider moving it to the side.": "편집기 창이 화면 중앙의 효과를 가릴 수 있습니다. 창을 옆으로 옮긴 뒤 확인해 보세요.",
    "The launch sites can be placed either on a fixed location, or be attached to\nan entity, such a ride vehicle. The Pick On Map button allows you to select a\nlocation in the park by clicking, or selecting the entity by clicking on it.\n\n": "발사 지점은 고정 위치에 놓거나 놀이기구 차량 같은 개체에 연결할 수\n있습니다. '지도에서 선택'을 누른 뒤 공원 위치나 개체를 클릭하세요.",
    "The listview will show you the various effects you've added in a load. Of\ncourse you'll want to test out how it looks, which is precisely what the\nTest Load button is for.\n\n": "목록에는 효과 묶음에 추가한 효과들이 표시됩니다.\n'효과 묶음 시험' 버튼으로 실제 모습을 확인할 수 있습니다.",
    "The number of ticks before the particles reach\ntheir max height. Affects life time of particles.": "입자가 최대 높이에 도달하기까지의 틱 수입니다.\n입자의 수명에도 영향을 줍니다.",
    "The process can be quite daunting at first but this tutorial will guide you\nthrough the basics and help you get started with creating your own fireworks\ndisplays.\n\nThe tabs in this tutorial correspond to the tabs in the main Fireworks Editor\nwindow and will provide you with an overview of each section and its": "처음에는 조금 복잡하게 느껴질 수 있지만 이 안내서에서\n기본 사용법과 나만의 불꽃놀이를 만드는 과정을 알려드립니다.\n이 안내서의 탭은 주 불꽃놀이 편집기의 탭과 같은 순서이며,\n각 항목의 기능을 간단히 설명합니다.",
    "The selected row is out of range.": "선택한 항목이 범위를 벗어났습니다.",
    "The type of sub-shells to use": "사용할 자탄 종류",
    "This allows to either insert and shift the rest of the sequence forward,\nor insert and merge. If you add an item after another item with a delay greater\nthan an already existing item after the index you're adding after, that is\npossible, but it will mean your new item does not appear directly after the\nindex you selected, but rather wherever it fits chronologically.": "따라서 항목을 삽입하면서 뒤쪽 시퀀스를 밀거나, 기존 시간대에 합칠 수 있습니다.\n기준 항목 뒤에 이미 있는 항목보다 더 긴 지연으로 새 항목을 추가하면,\n선택한 번호 바로 다음이 아니라 시간 순서에 맞는 위치에 표시됩니다.",
    "This final tab is the configuration tab. In here you can create\nColour-sequences, which are used by some effects such as the spray burst.\nThe plugin comes preloaded with a bunch, but you're free to adjust or \nremove them, and encouraged to create your own.\n\n": "마지막은 설정 탭입니다. 여기서 분사 폭발 같은 일부 효과에 쓰이는\n색상 시퀀스를 만들 수 있습니다. 여러 기본 시퀀스가 들어 있으며\n자유롭게 수정·삭제하거나 직접 만들 수 있습니다.",
    "This load is already used in a Shell of Shells, so another Shell of Shells cannot be added here.": "이 효과 묶음은 이미 자탄 폭발에서 사용 중이므로 여기에 또 다른 자탄 폭발을 추가할 수 없습니다.",
    "This park has been made with a Fireworks Show currently playing, made with the Fireworks Plugin. Please download the plugin to view the show at: ": "이 공원에는 불꽃놀이 플러그인으로 만든 공연이 재생 중입니다. 공연을 보려면 다음 주소에서 플러그인을 내려받으세요: ",
    "Three colours for the fish": "날치에 세 색상 사용",
    "Three colours mixed randomly": "세 색상을 무작위로 혼합",
    "Tilt": "기울기",
    "Tilt (0=up, 90=horiz)": "기울기(0=위, 90=수평)",
    "Time": "시간",
    "Time Till Stall": "정점 도달 시간",
    "Today": "오늘",
    "Too many loads": "효과 묶음이 너무 많음",
    "Tourbillion Rising Wisp": "상승 회오리",
    "Trail": "꼬리",
    "Trail 1": "꼬리 1",
    "Trail 1-2": "꼬리 1~2",
    "Trail 1A": "꼬리 1A",
    "Trail 1B": "꼬리 1B",
    "Trail 2": "꼬리 2",
    "Trail 2A": "꼬리 2A",
    "Trail 2B": "꼬리 2B",
    "Trail Colour": "꼬리 색상",
    "Trail Density": "꼬리 밀도",
    "Trail Width": "꼬리 폭",
    "Trigger type": "실행 조건 종류",
    "Two colours for the fish": "날치에 두 색상 사용",
    "Two colours mixed randomly": "두 색상을 무작위로 혼합",
    "Two halve spheres of different colours": "서로 다른 색상의 두 반구",
    "Two halve stars of different colours": "서로 다른 색상의 두 반쪽 별",
    "Two sets of colours, to be mixed randomly": "두 색상 조합을 무작위로 섞음",
    "Type": "종류",
    "Unfollow": "연결 해제",
    "Unknown": "알 수 없음",
    "Unlike shells, which pop once and are over then, some ground effects can\nlast a while, continuously emitting sparks.\nMuch like in the previous tabs, you can call the debugger, test out what\nyou made, and delete unwanted effects.": "한 번 터지고 끝나는 폭죽탄과 달리 일부 지상 효과는\n일정 시간 동안 불꽃을 계속 내보냅니다.\n앞의 탭처럼 디버거를 열고, 만든 효과를 시험하고, 필요 없는 효과를 삭제할 수 있습니다.",
    "Unsaved changes": "저장하지 않은 변경 사항",
    "Unsaved Editor": "저장되지 않은 편집 상태",
    "Update Effect": "효과 업데이트",
    "Update Phase": "단계 업데이트",
    "Useful as a lightweight placeholder shape, or when you just want a\nplain coloured pop without extra configuration.": "가벼운 임시 효과나 별도 설정 없는\n단순한 단색 폭발이 필요할 때 유용합니다.",
    "Using a colour sequence in random order": "색상 시퀀스를 무작위 순서로 사용",
    "Using a colour sequence in random order\nfor the fish": "날치에 색상 시퀀스를\n무작위 순서로 사용",
    "Value": "값",
    "Version: ": "버전: ",
    "Vertical Spread": "수직 분산",
    "Warning: Newer Fireworks Plugin Version: ": "경고: 더 최신 버전의 불꽃놀이 플러그인: ",
    "When a show starts, it can be made to be synced up with a ride's music.\nSelect a ride from the list, and right as the show starts, it will start\nplaying its ride music from the start, assuming the ride is opened and not\nbroken down.\n\n": "공연을 놀이기구 음악과 동기화할 수 있습니다. 목록에서 놀이기구를 선택하면\n공연 시작과 동시에 음악이 처음부터 재생됩니다. 놀이기구가 운행 중이고\n고장 나지 않은 상태여야 합니다.",
    "When you make a new launch site don't forget to pick a good name. If you\ndon't pick names, you'll just end up with a list of 'Site 1', 'Site 2' etc.,\nwhich isn't the clearest for finding back which is which later.\n\n": "새 발사 지점에는 알아보기 쉬운 이름을 붙이세요. 이름을 정하지 않으면\n'지점 1', '지점 2'처럼 저장되어 나중에 구분하기 어렵습니다.",
    "where you can see when the scheduled shows, and of course the stop button,\nto go back to the editor.": "이 창에서 예정된 공연 시간을 확인하고, 중지 버튼으로\n편집기로 돌아갈 수 있습니다.",
    "While shells form the spectacle of any given show, ground effects form the\nsupporting backbone role, like the bassist in band. The ground effects tab is\nsimilar to both shells and loads.\n\n Left is the editor, right is the list. Remember to name your ground effects.\n\n": "폭죽탄이 공연의 주인공이라면 지상 효과는 밴드의 베이스처럼 받쳐 줍니다.\n지상 효과 탭은 폭죽탄과 효과 묶음 탭을 합친 구조와 비슷합니다.\n왼쪽은 편집기, 오른쪽은 목록입니다. 지상 효과에도 이름을 붙이세요.",
    "Window Warning": "창 위치 경고",
    "Winter": "겨울",
    "Yearly": "매년",
    "Yes": "예",
    "You can also export and import data, which allows you to move your creations\nto other parks. Of course, the launch sites will not match up between parks\nand may land underground, or in the air.\n\n": "데이터를 내보내고 가져와 다른 공원으로 작품을 옮길 수도 있습니다.\n공원마다 지형이 다르므로 발사 지점이 지하나 공중에 놓일 수 있습니다.",
    "You will notice three input fields and two different 'add' buttons, as well as\ntwo little 'lock' checkmarks above sequence listview.\nThis can get tricky, so read carefully.\n\nYou can either add items AT a certain time, or some delay AFTER a certain item\nalready in the list.\n\n": "입력란 세 개와 서로 다른 추가 버튼 두 개, 목록 위의 고정 체크 두 개가\n보일 겁니다. 조금 복잡하니 아래 설명을 잘 읽어 보세요.\n항목을 특정 시간에 추가하거나, 목록의 특정 항목에서\n일정 시간 뒤에 실행되도록 추가할 수 있습니다."
};

Object.assign(koreanTranslations, {
});
